hepsi: derle calistir

derle:
	g++ -I ./include/ -o ./lib/Node.o -c ./src/Node.cpp
	g++ -I ./include/ -o ./lib/DoubleLinkedList.o -c ./src/DoubleLinkedList.cpp
	g++ -I ./include/ -o ./bin/test ./lib/Node.o ./lib/DoubleLinkedList.o ./src/test.cpp
	
calistir:
	./bin/test